const restaurant_Info = [
  {
    "rastaurant_name": "Restaurant 001",
    "rastaurant_image": `image/image.jpg`,
    "rating": 4.5,
    "Food_type": "Chinese",
    "price_to_for": 549,
    "Location": "Salt Lake, Kolkata",
    "Distance_for_Customer_House": "2.9 km",
    "Offers": "₹100 cashback (wallet)",
    "Alchol_server": true,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 002",
    "rastaurant_image": `image/image1.jpg`,
    "rating": 3.3,
    "Food_type": "Japanese",
    "price_to_for": 299,
    "Location": "Rajarhat, Kolkata",
    "Distance_for_Customer_House": "2.9 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 003",
    "rastaurant_image": `image/download.webp`,
    "rating": 3.6,
    "Food_type": "Continental",
    "price_to_for": 599,
    "Location": "Rajarhat, Kolkata",
    "Distance_for_Customer_House": "9.8 km",
    "Offers": "20% off up to ₹100",
    "Alchol_server": true,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 004",
    "rastaurant_image": "https://picsum.photos/seed/restaurant4/400/300",
    "rating": 3.5,
    "Food_type": "Mediterranean",
    "price_to_for": 699,
    "Location": "Esplanade, Kolkata",
    "Distance_for_Customer_House": "1.5 km",
    "Offers": "25% off for new users",
    "Alchol_server": true,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 005",
    "rastaurant_image": "https://picsum.photos/seed/restaurant5/400/300",
    "rating": 4.7,
    "Food_type": "Korean",
    "price_to_for": 999,
    "Location": "Esplanade, Kolkata",
    "Distance_for_Customer_House": "6.6 km",
    "Offers": "25% off for new users",
    "Alchol_server": true,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 006",
    "rastaurant_image": "https://picsum.photos/seed/restaurant6/400/300",
    "rating": 3.9,
    "Food_type": "Korean",
    "price_to_for": 499,
    "Location": "Malda",
    "Distance_for_Customer_House": "8.5 km",
    "Offers": "20% off up to ₹100",
    "Alchol_server": false,
    "rastaurant_open_time": "08:00 AM",
    "rastaurant_open_close": "08:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 007",
    "rastaurant_image": "https://picsum.photos/seed/restaurant7/400/300",
    "rating": 3.6,
    "Food_type": "South Indian",
    "price_to_for": 349,
    "Location": "Malda",
    "Distance_for_Customer_House": "4.7 km",
    "Offers": "Free dessert on orders above ₹499",
    "Alchol_server": false,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 008",
    "rastaurant_image": "https://picsum.photos/seed/restaurant8/400/300",
    "rating": 3.6,
    "Food_type": "Mexican",
    "price_to_for": 599,
    "Location": "Shyambazar, Kolkata",
    "Distance_for_Customer_House": "8.5 km",
    "Offers": "Super Saver: 30% off",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 009",
    "rastaurant_image": "https://picsum.photos/seed/restaurant9/400/300",
    "rating": 3.6,
    "Food_type": "Continental",
    "price_to_for": 999,
    "Location": "Kalyani",
    "Distance_for_Customer_House": "4.7 km",
    "Offers": "Super Saver: 30% off",
    "Alchol_server": false,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 010",
    "rastaurant_image": "https://picsum.photos/seed/restaurant10/400/300",
    "rating": 4.6,
    "Food_type": "Mediterranean",
    "price_to_for": 249,
    "Location": "Kharagpur",
    "Distance_for_Customer_House": "3.0 km",
    "Offers": "20% off up to ₹100",
    "Alchol_server": false,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 011",
    "rastaurant_image": "https://picsum.photos/seed/restaurant11/400/300",
    "rating": 4.8,
    "Food_type": "South Indian",
    "price_to_for": 699,
    "Location": "Ballygunge, Kolkata",
    "Distance_for_Customer_House": "2.8 km",
    "Offers": "Free dessert on orders above ₹499",
    "Alchol_server": false,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 012",
    "rastaurant_image": "https://picsum.photos/seed/restaurant12/400/300",
    "rating": 3.5,
    "Food_type": "Thai",
    "price_to_for": 599,
    "Location": "Esplanade, Kolkata",
    "Distance_for_Customer_House": "9.0 km",
    "Offers": "25% off for new users",
    "Alchol_server": false,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 013",
    "rastaurant_image": "https://picsum.photos/seed/restaurant13/400/300",
    "rating": 4.1,
    "Food_type": "Tandoori",
    "price_to_for": 299,
    "Location": "Gariahat, Kolkata",
    "Distance_for_Customer_House": "9.1 km",
    "Offers": "Free delivery on orders over ₹299",
    "Alchol_server": true,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 014",
    "rastaurant_image": "https://picsum.photos/seed/restaurant14/400/300",
    "rating": 3.3,
    "Food_type": "Biryani",
    "price_to_for": 799,
    "Location": "Barasat",
    "Distance_for_Customer_House": "7.3 km",
    "Offers": "Free dessert on orders above ₹499",
    "Alchol_server": false,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 015",
    "rastaurant_image": "https://picsum.photos/seed/restaurant15/400/300",
    "rating": 4.8,
    "Food_type": "Chinese",
    "price_to_for": 599,
    "Location": "Siliguri",
    "Distance_for_Customer_House": "9.3 km",
    "Offers": "15% off on UPI",
    "Alchol_server": true,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 016",
    "rastaurant_image": "https://picsum.photos/seed/restaurant16/400/300",
    "rating": 3.2,
    "Food_type": "Italian",
    "price_to_for": 599,
    "Location": "Camac Street, Kolkata",
    "Distance_for_Customer_House": "11.7 km",
    "Offers": "Flat ₹75 off",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 017",
    "rastaurant_image": "https://picsum.photos/seed/restaurant17/400/300",
    "rating": 3.6,
    "Food_type": "Bakery",
    "price_to_for": 749,
    "Location": "Barasat",
    "Distance_for_Customer_House": "9.2 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 018",
    "rastaurant_image": "https://picsum.photos/seed/restaurant18/400/300",
    "rating": 3.4,
    "Food_type": "Desserts",
    "price_to_for": 749,
    "Location": "Salt Lake, Kolkata",
    "Distance_for_Customer_House": "10.6 km",
    "Offers": "No current offers",
    "Alchol_server": true,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 019",
    "rastaurant_image": "https://picsum.photos/seed/restaurant19/400/300",
    "rating": 3.4,
    "Food_type": "Japanese",
    "price_to_for": 1099,
    "Location": "Park Street, Kolkata",
    "Distance_for_Customer_House": "9.8 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": true,
    "rastaurant_open_time": "08:00 AM",
    "rastaurant_open_close": "08:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 020",
    "rastaurant_image": "https://picsum.photos/seed/restaurant20/400/300",
    "rating": 3.7,
    "Food_type": "Continental",
    "price_to_for": 899,
    "Location": "Behala, Kolkata",
    "Distance_for_Customer_House": "11.6 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": false,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 021",
    "rastaurant_image": "https://picsum.photos/seed/restaurant21/400/300",
    "rating": 5.0,
    "Food_type": "Seafood",
    "price_to_for": 749,
    "Location": "Jadavpur, Kolkata",
    "Distance_for_Customer_House": "5.4 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 022",
    "rastaurant_image": "https://picsum.photos/seed/restaurant22/400/300",
    "rating": 3.8,
    "Food_type": "Tandoori",
    "price_to_for": 549,
    "Location": "Park Street, Kolkata",
    "Distance_for_Customer_House": "7.2 km",
    "Offers": "20% off up to ₹100",
    "Alchol_server": true,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 023",
    "rastaurant_image": "https://picsum.photos/seed/restaurant23/400/300",
    "rating": 4.8,
    "Food_type": "Tandoori",
    "price_to_for": 699,
    "Location": "Park Street, Kolkata",
    "Distance_for_Customer_House": "1.1 km",
    "Offers": "Buy 1 Get 1 Free (weekdays)",
    "Alchol_server": false,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 024",
    "rastaurant_image": "https://picsum.photos/seed/restaurant24/400/300",
    "rating": 3.4,
    "Food_type": "Mughlai",
    "price_to_for": 1099,
    "Location": "College Street, Kolkata",
    "Distance_for_Customer_House": "3.1 km",
    "Offers": "Free dessert on orders above ₹499",
    "Alchol_server": false,
    "rastaurant_open_time": "08:00 AM",
    "rastaurant_open_close": "08:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 025",
    "rastaurant_image": "https://picsum.photos/seed/restaurant25/400/300",
    "rating": 4.0,
    "Food_type": "Chinese",
    "price_to_for": 899,
    "Location": "Siliguri",
    "Distance_for_Customer_House": "5.1 km",
    "Offers": "₹100 cashback (wallet)",
    "Alchol_server": true,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 026",
    "rastaurant_image": "https://picsum.photos/seed/restaurant26/400/300",
    "rating": 4.5,
    "Food_type": "North Indian",
    "price_to_for": 349,
    "Location": "Jadavpur, Kolkata",
    "Distance_for_Customer_House": "3.2 km",
    "Offers": "Buy 1 Get 1 Free (weekdays)",
    "Alchol_server": false,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 027",
    "rastaurant_image": "https://picsum.photos/seed/restaurant27/400/300",
    "rating": 3.7,
    "Food_type": "Biryani",
    "price_to_for": 549,
    "Location": "Behala, Kolkata",
    "Distance_for_Customer_House": "10.5 km",
    "Offers": "Free delivery on orders over ₹299",
    "Alchol_server": false,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 028",
    "rastaurant_image": "https://picsum.photos/seed/restaurant28/400/300",
    "rating": 5.0,
    "Food_type": "North Indian",
    "price_to_for": 199,
    "Location": "Durgapur",
    "Distance_for_Customer_House": "11.6 km",
    "Offers": "Buy 1 Get 1 Free (weekdays)",
    "Alchol_server": true,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 029",
    "rastaurant_image": "https://picsum.photos/seed/restaurant29/400/300",
    "rating": 4.8,
    "Food_type": "Desserts",
    "price_to_for": 249,
    "Location": "Ballygunge, Kolkata",
    "Distance_for_Customer_House": "2.2 km",
    "Offers": "20% off up to ₹100",
    "Alchol_server": false,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 030",
    "rastaurant_image": "https://picsum.photos/seed/restaurant30/400/300",
    "rating": 4.5,
    "Food_type": "Seafood",
    "price_to_for": 1099,
    "Location": "Rajarhat, Kolkata",
    "Distance_for_Customer_House": "2.1 km",
    "Offers": "No current offers",
    "Alchol_server": true,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 031",
    "rastaurant_image": "https://picsum.photos/seed/restaurant31/400/300",
    "rating": 3.3,
    "Food_type": "Mediterranean",
    "price_to_for": 1099,
    "Location": "New Town, Kolkata",
    "Distance_for_Customer_House": "6.2 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": true,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 032",
    "rastaurant_image": "https://picsum.photos/seed/restaurant32/400/300",
    "rating": 4.3,
    "Food_type": "Italian",
    "price_to_for": 549,
    "Location": "Park Street, Kolkata",
    "Distance_for_Customer_House": "5.0 km",
    "Offers": "Bank offer: 10% instant discount",
    "Alchol_server": true,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 033",
    "rastaurant_image": "https://picsum.photos/seed/restaurant33/400/300",
    "rating": 4.0,
    "Food_type": "Korean",
    "price_to_for": 1199,
    "Location": "Park Street, Kolkata",
    "Distance_for_Customer_House": "4.0 km",
    "Offers": "No current offers",
    "Alchol_server": true,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 034",
    "rastaurant_image": "https://picsum.photos/seed/restaurant34/400/300",
    "rating": 3.9,
    "Food_type": "Tandoori",
    "price_to_for": 649,
    "Location": "Esplanade, Kolkata",
    "Distance_for_Customer_House": "5.6 km",
    "Offers": "Free delivery on orders over ₹299",
    "Alchol_server": true,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 035",
    "rastaurant_image": "https://picsum.photos/seed/restaurant35/400/300",
    "rating": 3.6,
    "Food_type": "South Indian",
    "price_to_for": 599,
    "Location": "College Street, Kolkata",
    "Distance_for_Customer_House": "1.8 km",
    "Offers": "15% off on UPI",
    "Alchol_server": true,
    "rastaurant_open_time": "08:00 AM",
    "rastaurant_open_close": "08:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 036",
    "rastaurant_image": "https://picsum.photos/seed/restaurant36/400/300",
    "rating": 4.0,
    "Food_type": "Seafood",
    "price_to_for": 649,
    "Location": "Behala, Kolkata",
    "Distance_for_Customer_House": "7.5 km",
    "Offers": "Super Saver: 30% off",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 037",
    "rastaurant_image": "https://picsum.photos/seed/restaurant37/400/300",
    "rating": 3.7,
    "Food_type": "Chinese",
    "price_to_for": 349,
    "Location": "Gariahat, Kolkata",
    "Distance_for_Customer_House": "9.0 km",
    "Offers": "Flat ₹75 off",
    "Alchol_server": false,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 038",
    "rastaurant_image": "https://picsum.photos/seed/restaurant38/400/300",
    "rating": 4.4,
    "Food_type": "Mediterranean",
    "price_to_for": 599,
    "Location": "Ballygunge, Kolkata",
    "Distance_for_Customer_House": "6.2 km",
    "Offers": "No current offers",
    "Alchol_server": true,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 039",
    "rastaurant_image": "https://picsum.photos/seed/restaurant39/400/300",
    "rating": 3.2,
    "Food_type": "Street Food",
    "price_to_for": 399,
    "Location": "New Town, Kolkata",
    "Distance_for_Customer_House": "7.8 km",
    "Offers": "No current offers",
    "Alchol_server": true,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 040",
    "rastaurant_image": "https://picsum.photos/seed/restaurant40/400/300",
    "rating": 4.0,
    "Food_type": "Continental",
    "price_to_for": 199,
    "Location": "Asansol",
    "Distance_for_Customer_House": "1.6 km",
    "Offers": "₹100 cashback (wallet)",
    "Alchol_server": true,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 041",
    "rastaurant_image": "https://picsum.photos/seed/restaurant41/400/300",
    "rating": 4.2,
    "Food_type": "Mexican",
    "price_to_for": 899,
    "Location": "Chandannagar",
    "Distance_for_Customer_House": "1.8 km",
    "Offers": "No current offers",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 042",
    "rastaurant_image": "https://picsum.photos/seed/restaurant42/400/300",
    "rating": 3.6,
    "Food_type": "Mughlai",
    "price_to_for": 349,
    "Location": "Siliguri",
    "Distance_for_Customer_House": "4.4 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": false,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 043",
    "rastaurant_image": "https://picsum.photos/seed/restaurant43/400/300",
    "rating": 3.5,
    "Food_type": "Tandoori",
    "price_to_for": 449,
    "Location": "Malda",
    "Distance_for_Customer_House": "10.6 km",
    "Offers": "20% off up to ₹100",
    "Alchol_server": true,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 044",
    "rastaurant_image": "https://picsum.photos/seed/restaurant44/400/300",
    "rating": 4.4,
    "Food_type": "Biryani",
    "price_to_for": 549,
    "Location": "Midnapore",
    "Distance_for_Customer_House": "3.4 km",
    "Offers": "₹100 cashback (wallet)",
    "Alchol_server": true,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 045",
    "rastaurant_image": "https://picsum.photos/seed/restaurant45/400/300",
    "rating": 3.6,
    "Food_type": "Desserts",
    "price_to_for": 999,
    "Location": "Dum Dum, Kolkata",
    "Distance_for_Customer_House": "4.4 km",
    "Offers": "Buy 1 Get 1 Free (weekdays)",
    "Alchol_server": true,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 046",
    "rastaurant_image": "https://picsum.photos/seed/restaurant46/400/300",
    "rating": 3.7,
    "Food_type": "Pizza",
    "price_to_for": 299,
    "Location": "Kasba, Kolkata",
    "Distance_for_Customer_House": "11.6 km",
    "Offers": "No current offers",
    "Alchol_server": false,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 047",
    "rastaurant_image": "https://picsum.photos/seed/restaurant47/400/300",
    "rating": 4.9,
    "Food_type": "Continental",
    "price_to_for": 349,
    "Location": "Kasba, Kolkata",
    "Distance_for_Customer_House": "10.6 km",
    "Offers": "No current offers",
    "Alchol_server": true,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 048",
    "rastaurant_image": "https://picsum.photos/seed/restaurant48/400/300",
    "rating": 4.3,
    "Food_type": "North Indian",
    "price_to_for": 749,
    "Location": "Howrah",
    "Distance_for_Customer_House": "8.8 km",
    "Offers": "15% off on UPI",
    "Alchol_server": false,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 049",
    "rastaurant_image": "https://picsum.photos/seed/restaurant49/400/300",
    "rating": 3.5,
    "Food_type": "Pizza",
    "price_to_for": 249,
    "Location": "Chandannagar",
    "Distance_for_Customer_House": "8.6 km",
    "Offers": "20% off up to ₹100",
    "Alchol_server": false,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 050",
    "rastaurant_image": "https://picsum.photos/seed/restaurant50/400/300",
    "rating": 3.3,
    "Food_type": "Mexican",
    "price_to_for": 699,
    "Location": "Rajarhat, Kolkata",
    "Distance_for_Customer_House": "7.6 km",
    "Offers": "Super Saver: 30% off",
    "Alchol_server": true,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 051",
    "rastaurant_image": "https://picsum.photos/seed/restaurant51/400/300",
    "rating": 4.4,
    "Food_type": "Bakery",
    "price_to_for": 699,
    "Location": "Tollygunge, Kolkata",
    "Distance_for_Customer_House": "5.0 km",
    "Offers": "No current offers",
    "Alchol_server": false,
    "rastaurant_open_time": "08:00 AM",
    "rastaurant_open_close": "08:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 052",
    "rastaurant_image": "https://picsum.photos/seed/restaurant52/400/300",
    "rating": 4.9,
    "Food_type": "Biryani",
    "price_to_for": 449,
    "Location": "Siliguri",
    "Distance_for_Customer_House": "7.5 km",
    "Offers": "No current offers",
    "Alchol_server": false,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 053",
    "rastaurant_image": "https://picsum.photos/seed/restaurant53/400/300",
    "rating": 3.6,
    "Food_type": "Seafood",
    "price_to_for": 699,
    "Location": "Tollygunge, Kolkata",
    "Distance_for_Customer_House": "5.7 km",
    "Offers": "Free dessert on orders above ₹499",
    "Alchol_server": false,
    "rastaurant_open_time": "08:00 AM",
    "rastaurant_open_close": "08:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 054",
    "rastaurant_image": "https://picsum.photos/seed/restaurant54/400/300",
    "rating": 3.4,
    "Food_type": "Italian",
    "price_to_for": 1199,
    "Location": "Siliguri",
    "Distance_for_Customer_House": "8.1 km",
    "Offers": "Bank offer: 10% instant discount",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 055",
    "rastaurant_image": "https://picsum.photos/seed/restaurant55/400/300",
    "rating": 4.7,
    "Food_type": "Seafood",
    "price_to_for": 399,
    "Location": "Dum Dum, Kolkata",
    "Distance_for_Customer_House": "0.6 km",
    "Offers": "Buy 1 Get 1 Free (weekdays)",
    "Alchol_server": false,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 056",
    "rastaurant_image": "https://picsum.photos/seed/restaurant56/400/300",
    "rating": 4.8,
    "Food_type": "Cafe",
    "price_to_for": 499,
    "Location": "Rajarhat, Kolkata",
    "Distance_for_Customer_House": "8.7 km",
    "Offers": "25% off for new users",
    "Alchol_server": false,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 057",
    "rastaurant_image": "https://picsum.photos/seed/restaurant57/400/300",
    "rating": 4.4,
    "Food_type": "Thai",
    "price_to_for": 349,
    "Location": "Durgapur",
    "Distance_for_Customer_House": "9.4 km",
    "Offers": "Buy 1 Get 1 Free (weekdays)",
    "Alchol_server": true,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 058",
    "rastaurant_image": "https://picsum.photos/seed/restaurant58/400/300",
    "rating": 3.6,
    "Food_type": "North Indian",
    "price_to_for": 349,
    "Location": "College Street, Kolkata",
    "Distance_for_Customer_House": "5.6 km",
    "Offers": "Free dessert on orders above ₹499",
    "Alchol_server": false,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 059",
    "rastaurant_image": "https://picsum.photos/seed/restaurant59/400/300",
    "rating": 4.7,
    "Food_type": "Cafe",
    "price_to_for": 1199,
    "Location": "Barasat",
    "Distance_for_Customer_House": "5.3 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": false,
    "rastaurant_open_time": "08:00 AM",
    "rastaurant_open_close": "08:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 060",
    "rastaurant_image": "https://picsum.photos/seed/restaurant60/400/300",
    "rating": 4.6,
    "Food_type": "Cafe",
    "price_to_for": 599,
    "Location": "Esplanade, Kolkata",
    "Distance_for_Customer_House": "9.3 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": false,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 061",
    "rastaurant_image": "https://picsum.photos/seed/restaurant61/400/300",
    "rating": 3.3,
    "Food_type": "Street Food",
    "price_to_for": 649,
    "Location": "Camac Street, Kolkata",
    "Distance_for_Customer_House": "3.0 km",
    "Offers": "15% off on UPI",
    "Alchol_server": false,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 062",
    "rastaurant_image": "https://picsum.photos/seed/restaurant62/400/300",
    "rating": 3.6,
    "Food_type": "Thai",
    "price_to_for": 399,
    "Location": "Gariahat, Kolkata",
    "Distance_for_Customer_House": "8.6 km",
    "Offers": "Free delivery on orders over ₹299",
    "Alchol_server": false,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 063",
    "rastaurant_image": "https://picsum.photos/seed/restaurant63/400/300",
    "rating": 3.9,
    "Food_type": "Continental",
    "price_to_for": 499,
    "Location": "Camac Street, Kolkata",
    "Distance_for_Customer_House": "10.0 km",
    "Offers": "25% off for new users",
    "Alchol_server": false,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 064",
    "rastaurant_image": "https://picsum.photos/seed/restaurant64/400/300",
    "rating": 4.1,
    "Food_type": "Japanese",
    "price_to_for": 749,
    "Location": "Jadavpur, Kolkata",
    "Distance_for_Customer_House": "3.8 km",
    "Offers": "25% off for new users",
    "Alchol_server": false,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 065",
    "rastaurant_image": "https://picsum.photos/seed/restaurant65/400/300",
    "rating": 3.7,
    "Food_type": "Desserts",
    "price_to_for": 1099,
    "Location": "Dum Dum, Kolkata",
    "Distance_for_Customer_House": "0.6 km",
    "Offers": "15% off on UPI",
    "Alchol_server": false,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 066",
    "rastaurant_image": "https://picsum.photos/seed/restaurant66/400/300",
    "rating": 4.0,
    "Food_type": "Italian",
    "price_to_for": 399,
    "Location": "Kharagpur",
    "Distance_for_Customer_House": "11.8 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": true,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 067",
    "rastaurant_image": "https://picsum.photos/seed/restaurant67/400/300",
    "rating": 4.0,
    "Food_type": "South Indian",
    "price_to_for": 999,
    "Location": "Durgapur",
    "Distance_for_Customer_House": "2.4 km",
    "Offers": "No current offers",
    "Alchol_server": false,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 068",
    "rastaurant_image": "https://picsum.photos/seed/restaurant68/400/300",
    "rating": 3.8,
    "Food_type": "Cafe",
    "price_to_for": 799,
    "Location": "Kasba, Kolkata",
    "Distance_for_Customer_House": "3.6 km",
    "Offers": "25% off for new users",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 069",
    "rastaurant_image": "https://picsum.photos/seed/restaurant69/400/300",
    "rating": 4.2,
    "Food_type": "Bengali",
    "price_to_for": 749,
    "Location": "Kalyani",
    "Distance_for_Customer_House": "2.9 km",
    "Offers": "Free delivery on orders over ₹299",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 070",
    "rastaurant_image": "https://picsum.photos/seed/restaurant70/400/300",
    "rating": 4.7,
    "Food_type": "Tandoori",
    "price_to_for": 399,
    "Location": "Ballygunge, Kolkata",
    "Distance_for_Customer_House": "3.1 km",
    "Offers": "Free dessert on orders above ₹499",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 071",
    "rastaurant_image": "https://picsum.photos/seed/restaurant71/400/300",
    "rating": 3.7,
    "Food_type": "Cafe",
    "price_to_for": 749,
    "Location": "Asansol",
    "Distance_for_Customer_House": "2.3 km",
    "Offers": "Bank offer: 10% instant discount",
    "Alchol_server": false,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 072",
    "rastaurant_image": "https://picsum.photos/seed/restaurant72/400/300",
    "rating": 3.4,
    "Food_type": "Italian",
    "price_to_for": 199,
    "Location": "Tollygunge, Kolkata",
    "Distance_for_Customer_House": "11.2 km",
    "Offers": "Bank offer: 10% instant discount",
    "Alchol_server": false,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 073",
    "rastaurant_image": "https://picsum.photos/seed/restaurant73/400/300",
    "rating": 4.3,
    "Food_type": "Mughlai",
    "price_to_for": 549,
    "Location": "Park Street, Kolkata",
    "Distance_for_Customer_House": "1.5 km",
    "Offers": "No current offers",
    "Alchol_server": false,
    "rastaurant_open_time": "11:00 AM",
    "rastaurant_open_close": "11:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 074",
    "rastaurant_image": "https://picsum.photos/seed/restaurant74/400/300",
    "rating": 3.3,
    "Food_type": "Japanese",
    "price_to_for": 899,
    "Location": "Midnapore",
    "Distance_for_Customer_House": "8.0 km",
    "Offers": "Free delivery on orders over ₹299",
    "Alchol_server": false,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 075",
    "rastaurant_image": "https://picsum.photos/seed/restaurant75/400/300",
    "rating": 4.0,
    "Food_type": "Bengali",
    "price_to_for": 1099,
    "Location": "Malda",
    "Distance_for_Customer_House": "1.5 km",
    "Offers": "15% off on UPI",
    "Alchol_server": false,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 076",
    "rastaurant_image": "https://picsum.photos/seed/restaurant76/400/300",
    "rating": 4.5,
    "Food_type": "Biryani",
    "price_to_for": 599,
    "Location": "Behala, Kolkata",
    "Distance_for_Customer_House": "7.5 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": false,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 077",
    "rastaurant_image": "https://picsum.photos/seed/restaurant77/400/300",
    "rating": 3.8,
    "Food_type": "Japanese",
    "price_to_for": 549,
    "Location": "Esplanade, Kolkata",
    "Distance_for_Customer_House": "10.0 km",
    "Offers": "Free delivery on orders over ₹299",
    "Alchol_server": false,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 078",
    "rastaurant_image": "https://picsum.photos/seed/restaurant78/400/300",
    "rating": 4.3,
    "Food_type": "Cafe",
    "price_to_for": 799,
    "Location": "Chandannagar",
    "Distance_for_Customer_House": "4.2 km",
    "Offers": "Free dessert on orders above ₹499",
    "Alchol_server": false,
    "rastaurant_open_time": "08:00 AM",
    "rastaurant_open_close": "08:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 079",
    "rastaurant_image": "https://picsum.photos/seed/restaurant79/400/300",
    "rating": 4.6,
    "Food_type": "Mughlai",
    "price_to_for": 699,
    "Location": "Shyambazar, Kolkata",
    "Distance_for_Customer_House": "3.6 km",
    "Offers": "Bank offer: 10% instant discount",
    "Alchol_server": false,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 080",
    "rastaurant_image": "https://picsum.photos/seed/restaurant80/400/300",
    "rating": 3.4,
    "Food_type": "Bakery",
    "price_to_for": 899,
    "Location": "Ballygunge, Kolkata",
    "Distance_for_Customer_House": "6.0 km",
    "Offers": "Buy 1 Get 1 Free (weekdays)",
    "Alchol_server": false,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 081",
    "rastaurant_image": "https://picsum.photos/seed/restaurant81/400/300",
    "rating": 3.2,
    "Food_type": "Cafe",
    "price_to_for": 649,
    "Location": "Midnapore",
    "Distance_for_Customer_House": "2.9 km",
    "Offers": "₹100 cashback (wallet)",
    "Alchol_server": true,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 082",
    "rastaurant_image": "https://picsum.photos/seed/restaurant82/400/300",
    "rating": 4.2,
    "Food_type": "Desserts",
    "price_to_for": 899,
    "Location": "College Street, Kolkata",
    "Distance_for_Customer_House": "12.0 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": false,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 083",
    "rastaurant_image": "https://picsum.photos/seed/restaurant83/400/300",
    "rating": 3.7,
    "Food_type": "Street Food",
    "price_to_for": 349,
    "Location": "Tollygunge, Kolkata",
    "Distance_for_Customer_House": "8.7 km",
    "Offers": "15% off on UPI",
    "Alchol_server": true,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 084",
    "rastaurant_image": "https://picsum.photos/seed/restaurant84/400/300",
    "rating": 4.5,
    "Food_type": "Mughlai",
    "price_to_for": 599,
    "Location": "Ballygunge, Kolkata",
    "Distance_for_Customer_House": "8.8 km",
    "Offers": "Combo meals from ₹199",
    "Alchol_server": false,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 085",
    "rastaurant_image": "https://picsum.photos/seed/restaurant85/400/300",
    "rating": 3.6,
    "Food_type": "Mughlai",
    "price_to_for": 449,
    "Location": "Tollygunge, Kolkata",
    "Distance_for_Customer_House": "3.8 km",
    "Offers": "₹100 cashback (wallet)",
    "Alchol_server": false,
    "rastaurant_open_time": "08:00 AM",
    "rastaurant_open_close": "08:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 086",
    "rastaurant_image": "https://picsum.photos/seed/restaurant86/400/300",
    "rating": 4.2,
    "Food_type": "North Indian",
    "price_to_for": 399,
    "Location": "New Town, Kolkata",
    "Distance_for_Customer_House": "7.8 km",
    "Offers": "Free dessert on orders above ₹499",
    "Alchol_server": true,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 087",
    "rastaurant_image": "https://picsum.photos/seed/restaurant87/400/300",
    "rating": 4.0,
    "Food_type": "Desserts",
    "price_to_for": 449,
    "Location": "Shakespeare Sarani, Kolkata",
    "Distance_for_Customer_House": "11.6 km",
    "Offers": "No current offers",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 08:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 088",
    "rastaurant_image": "https://picsum.photos/seed/restaurant88/400/300",
    "rating": 3.3,
    "Food_type": "Pizza",
    "price_to_for": 249,
    "Location": "Shakespeare Sarani, Kolkata",
    "Distance_for_Customer_House": "2.1 km",
    "Offers": "Bank offer: 10% instant discount",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 089",
    "rastaurant_image": "https://picsum.photos/seed/restaurant89/400/300",
    "rating": 4.6,
    "Food_type": "Chinese",
    "price_to_for": 549,
    "Location": "College Street, Kolkata",
    "Distance_for_Customer_House": "9.4 km",
    "Offers": "25% off for new users",
    "Alchol_server": false,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 090",
    "rastaurant_image": "https://picsum.photos/seed/restaurant90/400/300",
    "rating": 3.7,
    "Food_type": "Japanese",
    "price_to_for": 249,
    "Location": "Rajarhat, Kolkata",
    "Distance_for_Customer_House": "7.4 km",
    "Offers": "₹100 cashback (wallet)",
    "Alchol_server": true,
    "rastaurant_open_time": "08:00 AM",
    "rastaurant_open_close": "08:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 091",
    "rastaurant_image": "https://picsum.photos/seed/restaurant91/400/300",
    "rating": 3.3,
    "Food_type": "Street Food",
    "price_to_for": 549,
    "Location": "Siliguri",
    "Distance_for_Customer_House": "2.3 km",
    "Offers": "Free delivery on orders over ₹299",
    "Alchol_server": true,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 092",
    "rastaurant_image": "https://picsum.photos/seed/restaurant92/400/300",
    "rating": 4.3,
    "Food_type": "Cafe",
    "price_to_for": 649,
    "Location": "Asansol",
    "Distance_for_Customer_House": "0.7 km",
    "Offers": "No current offers",
    "Alchol_server": false,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 093",
    "rastaurant_image": "https://picsum.photos/seed/restaurant93/400/300",
    "rating": 3.6,
    "Food_type": "South Indian",
    "price_to_for": 599,
    "Location": "Siliguri",
    "Distance_for_Customer_House": "9.5 km",
    "Offers": "Super Saver: 30% off",
    "Alchol_server": false,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 094",
    "rastaurant_image": "https://picsum.photos/seed/restaurant94/400/300",
    "rating": 4.2,
    "Food_type": "Biryani",
    "price_to_for": 399,
    "Location": "Howrah",
    "Distance_for_Customer_House": "10.9 km",
    "Offers": "Flat ₹75 off",
    "Alchol_server": true,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 095",
    "rastaurant_image": "https://picsum.photos/seed/restaurant95/400/300",
    "rating": 4.5,
    "Food_type": "Seafood",
    "price_to_for": 649,
    "Location": "Barasat",
    "Distance_for_Customer_House": "5.4 km",
    "Offers": "Free dessert on orders above ₹499",
    "Alchol_server": false,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 11:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 096",
    "rastaurant_image": "https://picsum.photos/seed/restaurant96/400/300",
    "rating": 4.2,
    "Food_type": "Street Food",
    "price_to_for": 999,
    "Location": "Sealdah, Kolkata",
    "Distance_for_Customer_House": "1.2 km",
    "Offers": "20% off up to ₹100",
    "Alchol_server": false,
    "rastaurant_open_time": "12:00 PM",
    "rastaurant_open_close": "12:00 PM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 097",
    "rastaurant_image": "https://picsum.photos/seed/restaurant97/400/300",
    "rating": 3.2,
    "Food_type": "Korean",
    "price_to_for": 549,
    "Location": "Esplanade, Kolkata",
    "Distance_for_Customer_House": "11.6 km",
    "Offers": "Bank offer: 10% instant discount",
    "Alchol_server": false,
    "rastaurant_open_time": "07:00 AM",
    "rastaurant_open_close": "07:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 098",
    "rastaurant_image": "https://picsum.photos/seed/restaurant98/400/300",
    "rating": 4.6,
    "Food_type": "Japanese",
    "price_to_for": 449,
    "Location": "New Town, Kolkata",
    "Distance_for_Customer_House": "5.8 km",
    "Offers": "Super Saver: 30% off",
    "Alchol_server": false,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 09:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 099",
    "rastaurant_image": "https://picsum.photos/seed/restaurant99/400/300",
    "rating": 4.3,
    "Food_type": "Japanese",
    "price_to_for": 1099,
    "Location": "Rajarhat, Kolkata",
    "Distance_for_Customer_House": "11.6 km",
    "Offers": "Free dessert on orders above ₹499",
    "Alchol_server": false,
    "rastaurant_open_time": "10:00 AM",
    "rastaurant_open_close": "10:00 AM - 10:00 PM"
  },
  {
    "rastaurant_name": "Restaurant 100",
    "rastaurant_image": "https://picsum.photos/seed/restaurant100/400/300",
    "rating": 3.4,
    "Food_type": "Mediterranean",
    "price_to_for": 449,
    "Location": "Siliguri",
    "Distance_for_Customer_House": "4.2 km",
    "Offers": "₹100 cashback (wallet)",
    "Alchol_server": false,
    "rastaurant_open_time": "09:00 AM",
    "rastaurant_open_close": "09:00 AM - 11:00 PM"
  }
];

 

    const container = document.getElementById("restaurant-list");

    restaurant_Info.forEach(r => {
      const card = document.createElement("div");
      card.className = "card";
      

      

      card.innerHTML = `
        <div class="card-body">
        <img src="${r.rastaurant_image}" alt="${r.rastaurant_name}"></img>
          <h2>${r.rastaurant_name}</h2>
          <p class="rating">⭐ ${r.rating}</p>
          <p><strong>Food:</strong> ${r.Food_type}</p>
          <p><strong>Price for two:</strong> ₹${r.price_to_for}</p>
          <p><strong>Location:</strong> ${r.Location}</p>
          <p><strong>Distance:</strong> ${r.Distance_for_Customer_House}</p>
          <p class="offer">${r.Offers}</p>
          <p><strong>Alcohol:</strong> ${r.Alchol_server ? "Yes 🍷" : "No 🚫"}</p>
          <p><strong>Timings:</strong> ${r.rastaurant_open_close}</p>
        </div>
      `;
      container.appendChild(card);
    });